name: Build image and push to Docker Hub

on:
  workflow_dispatch:
  schedule:
    - cron: '26 12 * * *'
  push:
    branches:
      - '7.3'
      - '7.4'
      - '8.0'


env:
  # BRANCH: '7.3'
  APACHE_WORKFLOW_ID: '8995258'
  SWOOLE_WORKFLOW_ID: '8996324'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        version: ['base', 'mssql', 'xdebug', 'mssql-xdebug']
        branch: ['7.3', '7.4', '8.0']

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Create tag name
        id: build-tag
        run: |
          if [[ ${{ matrix.version }} == 'base' ]]; then
              echo "::set-output name=tag::"
          else
              echo "::set-output name=tag::-${{ matrix.version }}"
          fi
      -
        name: Build latest
        if: ${{ matrix.branch == '8.3' && matrix.version == 'base' }}
        uses: docker/build-push-action@v2
        with:
          context: ./base
          push: true
          platforms: ${{ secrets.DOCKER_PLATFORMS }}
          tags: rshop/php:latest
      -
        name: Build ${{ matrix.version }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.version }}
          push: true
          platforms: ${{ secrets.DOCKER_PLATFORMS }}
          tags: rshop/php:${{ matrix.branch }}${{ steps.build-tag.outputs.tag }}
      -
        name: Trigger apache ${{ matrix.version }} rebuild
        uses: rshop/trigger-workflow-action@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: 'rshop/docker-php-apache'
          workflowId: ${{ env.APACHE_WORKFLOW_ID }}
          branch: ${{ matrix.branch }}${{ steps.build-tag.outputs.tag }}
      -
        name: Trigger swoole ${{ matrix.version }} rebuild
        if: ${{ !contains(matrix.version, 'xdebug') }}
        uses: rshop/trigger-workflow-action@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: 'rshop/docker-swoole'
          workflowId: ${{ env.SWOOLE_WORKFLOW_ID }}
          branch: ${{ matrix.branch }}${{ steps.build-tag.outputs.tag }}