name: Build image and push to Docker Hub

on:
  push:
    branches:
      - '7.3'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build base
        uses: docker/build-push-action@v2
        with:
          context: /base
          push: true
          tags: rshop/php:7.3,rshop/php:latest
      -
        name: Build mssql
        uses: docker/build-push-action@v2
        with:
          context: /mssql
          push: true
          tags: rshop/php:7.3-mssql
      -
        name: Build xdebug
        uses: docker/build-push-action@v2
        with:
          context: /xdebug
          push: true
          tags: rshop/php:7.3-xdebug
      -
        name: Build mssql-xdebug
        uses: docker/build-push-action@v2
        with:
          context: /mssql-xdebug
          push: true
          tags: rshop/php:7.3-mssql-xdebug