name: Build image and push to Docker Hub

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
  schedule:
    - cron: '4 12 * * *'

env:
  APACHE_WORKFLOW_ID: '8995258'
  SWOOLE_WORKFLOW_ID: '8996324'

jobs:
  build-branch:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        branch: ['7.3', '7.4', '8.0']  # Add any other branches here

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - name: Build images for each version in branch ${{ matrix.branch }}
        uses: actions/github-script@v6
        with:
          script: |
            const versions = ['base', 'mssql', 'xdebug', 'mssql-xdebug'];
            for (const version of versions) {
              await github.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'build.yml',
                ref: matrix.branch,
                inputs: { version, branch: matrix.branch }
              });
            }

      - name: Delay before next branch
        if: ${{ !endsWith(matrix.branch, '8.0') }}  # Skip delay for the last branch
        run: |
          echo "Waiting for 20 minutes before starting the next branch..."
          sleep 1200
