name: Schedule Branch Builds

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '56 7 * * *' 

jobs:
  push_to_branches:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - { name: '7.3', delay: 0 }
          - { name: '7.4', delay: 10 }
          - { name: '8.0', delay: 20 }

    steps:
      - name: Introduce delay
        run: sleep ${{ matrix.branch.delay }}

      - name: Trigger build workflow on ${{ matrix.branch.name }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'MasaKni',
              repo: 'docker-php',
              workflow_id: 'build.yml',
              ref: '${{ matrix.branch.name }}',
              inputs: {}
            })
          github-token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Configure Git
      #   run: |
      #     git config --global user.name "github-actions"
      #     git config --global user.email "github-actions@github.com"

      # - name: Checkout branch
      #   uses: actions/checkout@v2
      #   with:
      #     ref: ${{ matrix.branch.name }}
      #     fetch-depth: 0

      # - name: Push to Branch with PAT
      #   env:
      #     PAT: ${{ secrets.ACCESS_TOKEN }}
      #   run: |
      #     git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}
      #     git commit --allow-empty -m "Scheduled trigger for branch ${{ matrix.branch.name }}"
      #     git push origin ${{ matrix.branch.name }}